name: Compilar ISO PSP
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pspdev/pspdev:latest
    steps:
      - uses: actions/checkout@v4

      - name: Compilar C++
        run: make

      - name: Instalar herramientas y armar estructura
        run: |
          apt-get update && apt-get install -y genisoimage
          mkdir -p ISO_ROOT/PSP_GAME/SYSDIR
          cp ArbitroPSP.elf ISO_ROOT/PSP_GAME/SYSDIR/EBOOT.BIN
          cp PARAM.SFO ISO_ROOT/PSP_GAME/PARAM.SFO
          echo "11111111111111111111111111111111|0000000000000000|0024|1|0" > ISO_ROOT/UMD_DATA.BIN

      - name: Crear archivo ISO
        run: |
          genisoimage -o JuegoArbitro.iso -r ISO_ROOT

      - name: Subir ISO Final
        uses: actions/upload-artifact@v4
        with:
          name: ISO_Para_PPSSPP
          path: JuegoArbitro.iso
